apiVersion: v2
name: issue-tracker
description: A small, authenticated issue tracker for shared teams
type: application
version: 0.12.0
appVersion: "0.12.0"
home: https://github.com/ricsam/issue-tracker
sources:
  - https://github.com/ricsam/issue-tracker
maintainers:
  - name: ricsam
    url: https://github.com/ricsam
